SKILL_VALUES = {'athletics': {20: 'delicate', 40: 'lethargic', 60: 'passive', 80: 'power walker',
                              100: 'huttball participant', 120: 'sprinter', 140: 'vigorous', 160: 'athlete',
                              180: 'smashball hero', 200: 'physical specimen', 201: 'hercules'},
                'business': {20: 'rube', 40: 'paper boy', 60: 'vendor', 80: 'shop owner', 100: 'spice trader',
                             120: 'banker', 140: 'manager', 160: 'entrepreneur', 180: 'hutt', 200: 'magnate',
                             201: 'mr. monopoly'},
                'command': {20: 'follower', 40: 'member', 60: 'supporter', 80: 'lead from the middle',
                            100: 'roger, roger', 120: 'officer', 140: 'commandant', 160: 'commander',
                            180: 'thrawn\'s legacy', 200: 'general', 201: 'president skroob'},
                'dodge': {20: 'clumsy', 40: 'unbalanced', 60: 'squirrely', 80: 'slippery', 100: 'boba fett\'s jetpack',
                          120: 'nimble', 140: 'deft', 160: 'adroit', 180: 'jedi reflexes', 200: 'untouchable',
                          201: 'neo from the matrix'},
                'explosives': {20: 'all thumbs', 40: 'cherry bomber', 60: 'rock show technician', 80: 'fireworker',
                               100: 'thermal detonator negotiator', 120: 'bomb tech', 140: 'pyro expert',
                               160: 'in the hurtlocker', 180: 'toss me those charges.', 200: 'boom bringer',
                               201: 'bomb voyage'},
                'firearms': {20: 'pea shooter', 40: 'slingshot user', 60: 'where\'s that barn at?',
                             80: 'gun range instructor', 100: 'stormtrooper', 120: 'marksman', 140: 'trick shot',
                             160: 'sniper', 180: 'bounty hunter', 200: 'one shot, one kill', 201: 'dirty harry'},
                'gambling': {20: 'sucker', 40: 'unlucky', 60: 'solitaire loser', 80: 'solitaire winner',
                             100: 'know when to hold \'em', 120: 'sabbac player', 140: 'pazaak dealer',
                             160: 'aces high', 180: 'know when to fold \'em', 200: 'lando\'s bane',
                             201: 'never tell me the odds'},
                'heavy weapons': {20: 'this is the dangerous end.', 40: 'spray and pray', 60: 'pew pew',
                                  80: 'controlled bursts', 100: 'say hello to my little friend', 120: 'grenadier',
                                  140: 'artilleryman', 160: 'force of nature', 180: 'this is my boomstick.',
                                  200: 'machine gun kelly', 201: 'i\'ll be back'},
                'influence': {20: 'zoidberg', 40: 'dewback oil salesman', 60: 'holomercial announcer',
                              80: 'used ship sales', 100: 'i love you.', 120: 'toast master',
                              140: 'master of ceremonies', 160: 'politician', 180: 'i know.', 200: 'chancellor',
                              201: 'ron burgundy'},
                'intellect': {20: 'slept through class', 40: 'student', 60: 'tutor', 80: 'teacher', 100: 'trekker',
                              120: 'professor', 140: 'researcher', 160: 'scientist', 180: 'droid brain',
                              200: 'free-thinker', 201: 'hephen stawking'},
                'mechanical': {20: 'what\'s a hydrospanner?', 40: 'use angie\'s list', 60: 'pumps own gas',
                               80: 'change the oil', 100: 'they told me they fixed it.', 120: 'monkeywrench',
                               140: 'my name is allen.  allen wrench.', 160: 'socket wiz', 180: 'it\'s not my fault.',
                               200: 'master engineer', 201: 'i\'m giving her all she\'s got!'},
                'medicine': {20: 'rub dirt on it', 40: 'walk it off', 60: 'first aid certified', 80: 'medic',
                             100: 'bacta hands', 120: 'doctor', 140: 'surgeon', 160: 'specialist',
                             180: 'he\'s only mostly dead', 200: 'i\'m a doctor, not a bantha!', 201: 'miracle max'},
                'melee': {20: 'slap fighter', 40: 'yellow belt', 60: 'competitor', 80: 'dojo owner',
                          100: 'kung fu hustle', 120:'shadow boxer', 140: 'martial artist', 160: 'black belt',
                          180: 'bruce lee', 200: 'welcome to the thunderdome.', 201: 'roadhouse!'},
                'perception': {20: 'i was blind.', 40: 'captain obvious', 60: 'not the sharpest tool',
                               80: 'watch that crossfire boys.', 100: 'into the garbage chute, flyboy', 120: 'astute',
                               140: 'observant', 160: 'insightful', 180: 'i could almost see the remote.',
                               200: 'now i see.', 201: 'madame cleo'},
                'piloting': {20: 'cardboard jockey', 40: 'soapbox racer', 60: 'pig rider', 80: 'womprat targeter',
                             100: 'red 5 standing by.', 120: 'squadron leader', 140: 'wing commander', 160: 'cag',
                             180: 'he turned off his computer!', 200: 'figher ace', 201: 'we don\'t need roads.'},
                'quickdraw': {20: 'where\'s the holster?', 40: 'slothdraw', 60: 'foot shooter', 80: 'near miss',
                              100: 'greedo shot first', 120: 'hot shot', 140: 'fast hands', 160: 'lightning jack',
                              180: 'han shot first', 200: 'i\'m your huckleberry.', 201: 'wyatt earp'},
                'salvage': {20: 'nit picker', 40: 'scavenger', 60: 'trash gatherer', 80: 'storage warrior',
                            100: 'jawa competition', 120: 'one man\'s trash.', 140: 'another man\'s treasure.',
                            160: 'needle in a haystack', 180: 'watto\'s bargains', 200: 'the collector',
                            201: 'rocket\'s creations'},
                'security': {20: 'i\'ll build a gui in vb.', 40: 'my password is 12345', 60: 'phishing victim',
                             80: 'locks the back door', 100: 'i guess i can hotwire this thing.', 120: 'it guy',
                             140: 'it\'s a unix system', 160: 'computer savant',
                             180: 'r2 can interpret the entire network', 200: 'hacker', 201: 'lawnmower man'},
                'stealth': {20: 'walking carpet', 40: 'clod hopper', 60: 'lead foot', 80: 'sneaky',
                            100: 'wampa in snow', 120: 'sure footed', 140: 'quiet as a mouse droid',
                            160: 'did you see that?', 180: 'dianoga in water', 200: 'i am the shadow.',
                            201: 'hayden\'s acting (invisible)'},
                'streetwise': {20: 'yuppie', 40: 'hipster', 60: 'justin beiber', 80: 'hood rat', 100: 'deathsticks?',
                               120: 'gangster', 140: 'boy in the \'hood', 160: 'where the streets have no names',
                               180: 'this place can be a little rough.', 200: 'captain jack sparrow',
                               201: 'my name is porter'},
                'survival': {20: 'castaway', 40: 'bird watcher', 60: 'shortcut to mushrooms', 80: 'trail blazer',
                             100: 'i thought she was with you!', 120: 'hiker', 140: 'camper', 160: 'mountaineer',
                             180: 'taun taun sleeping bag', 200: 'prepper', 201: 'survivorman'}}
