SPECIES = {"wookiee": {"skills": {"mechanical": 1, "stealth": -1}, "talents": {}},
           "human": {},
           "aqualish": {"melee": 1, "influence": -1},
           "arcona": {},
           "arkanian": {"perception": 1, "streetwise": -1},
           "barabel": {"dodge": 1, "survival": -1},
           "bith": { "perception": 1, "athletics": -1},
           "bothan": {"stealth": 1, "business": -1},
           "chadra-fan": {"perception": 1, "heavy weapons": -1},
           "chiss": {"command": 1, "gambling": -1},
           "devaronian": {},
           "dug": {"althletics": 1, "quickdraw": -1},
           "duros": {"piloting": 1, "explosives": -1},
           "falleen": {"influence": 1, "salvage": -1},
           "gamorrean": {"melee": 1, "mechanical": -1},
           "gand": {"perception": 1, "medicine": -1},
           "gran": {"business": 1, "streetwise": -1},
           "gungan": {"melee": 1, "streetwise": -1},
           "hutt": {"business": 1, "athletics": -1},
           "ishi tib": {"perception": 1, "survival": -1},
           "ithorian": {"intellect": 1, "firearms": -1},
           "kubaz": {"intellect": 1, "gambling": -1},
           "mon calamari": {"command": 1, "survival": -1},
           "neimoidian": {"business": 1, "perception": -1},
           "nikto": {"survival": 1, "command": -1},
           "quarren": {"piloting": 1, "influence": -1},
           "rodian": {"firearms": 1, "intellect": -1},
           "shistavanen": {"athletics": 1, "influence": -1},
           "sullustan": {"business": 1, "command": -1},
           "talz": {"heavy weapons": 1, "intellect": -1},
           "togorian": {"melee": 1, "security": -1},
           "twi'lek": {},
           "weequay": {"firearms": 1, "influence": -1},
           "whiphid": {"survival": 1, "mechanical": -1},
           "zeltron": {"influence": 1, "intellect": -1},
           "nagai": {"firearms": 1, "perception": -1}
          }
