# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0009_remove_objectdb_db_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_key', models.CharField(db_index=True, max_length=50)),
                ('db_credits', models.BigIntegerField(default=0)),
                ('db_resources', models.BigIntegerField(default=0)),
                ('db_active', models.BooleanField()),
                ('db_motd', models.TextField()),
                ('db_desc', models.CharField(max_length=250)),
                ('db_assets', models.ManyToManyField(null=True, to='objects.ObjectDB')),
                ('db_branches', models.ManyToManyField(null=True, to='objects.ObjectDB')),
                ('db_child_orgs', models.ManyToManyField(null=True, to='orgs.Org')),
                ('db_headquarters', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.ObjectDB')),
            ],
        ),
        migrations.CreateModel(
            name='OrgMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_rank', models.CharField(max_length=50, null=True)),
                ('db_assignment', models.CharField(max_length=50, null=True)),
                ('db_assigned_assets', models.ManyToManyField(null=True, to='objects.ObjectDB')),
                ('db_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.ObjectDB')),
                ('db_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Org')),
            ],
        ),
        migrations.AddField(
            model_name='org',
            name='db_leaders',
            field=models.ManyToManyField(null=True, related_name='leaders', to='orgs.OrgMember'),
        ),
        migrations.AddField(
            model_name='org',
            name='db_members',
            field=models.ManyToManyField(null=True, related_name='members', to='orgs.OrgMember'),
        ),
        migrations.AddField(
            model_name='org',
            name='db_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.Org'),
        ),
        migrations.AddField(
            model_name='org',
            name='db_pending',
            field=models.ManyToManyField(null=True, to='objects.ObjectDB'),
        ),
    ]
